version: 2.1
orbs:
  node: circleci/node@5.0.3
  aws-cli: circleci/aws-cli@3.1.3
jobs:
  build:
    docker:
      - image: "circleci/node@5.0.3"
    steps:
      - node/install
      - checkout
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            npm run backend:build